apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: prod
  labels:
    app: notification-service
    team: platform
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 8093
      targetPort: 8093
      protocol: TCP
